apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    env: production
spec:
  containers:
  - name: redis
    image: redis
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
