apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: busybox-replicaset
  labels:
    app: busybox
    type: front-end

spec:
  template:
    
    metadata:
      name: busybox-pod
      labels:
        app: busybox
        type: front-end
    spec:
      containers:
      - name: busybox
        image: busybox
  replicas: 4
  selector:
    matchLabels:
      type: front-end